package com.paddykim.platform.portal.source;

import java.time.Instant;

public record BuildProfileRunResponse(
        Long sourceRepositoryId,
        Long buildProfileId,
        String buildProfileName,
        Long historyId,
        Long executionId,
        Long portalRequestId,
        String repositoryName,
        String repositoryUrl,
        BuildProfileCiTool ciTool,
        String workingDirectory,
        String requestedBy,
        String requestedValue,
        String branch,
        String dispatchTarget,
        String status,
        String statusMessage,
        String cloneStatus,
        String cloneMessage,
        String checkoutPath,
        Integer exitCode,
        String logSummary,
        String imageRepository,
        String imageTag,
        String imageDigest,
        String imageReference,
        String manifestUpdateStatus,
        String manifestUpdateMessage,
        String manifestChangedFilePath,
        Instant manifestUpdatedAt,
        Instant startedAt,
        Instant finishedAt,
        Instant createdAt
) {

    static BuildProfileRunResponse from(
            Long sourceRepositoryId,
            Long buildProfileId,
            String buildProfileName,
            String repositoryName,
            String repositoryUrl,
            BuildProfileCiTool ciTool,
            String workingDirectory,
            String requestedBy,
            String requestedValue,
            String branch,
            String dispatchTarget,
            Long historyId,
            PlatformCicdExecutionResponse execution,
            BuildExecutionHistory history
    ) {
        return new BuildProfileRunResponse(
                sourceRepositoryId,
                buildProfileId,
                buildProfileName,
                historyId,
                execution.executionId(),
                execution.portalRequestId(),
                repositoryName,
                repositoryUrl,
                ciTool,
                workingDirectory,
                requestedBy,
                requestedValue,
                branch,
                dispatchTarget,
                execution.status(),
                execution.statusMessage(),
                execution.cloneStatus(),
                execution.cloneMessage(),
                execution.checkoutPath(),
                execution.exitCode(),
                execution.logSummary(),
                history.getImageRepository(),
                history.getImageTag(),
                history.getImageDigest(),
                history.getImageReference(),
                history.getManifestUpdateStatus(),
                history.getManifestUpdateMessage(),
                history.getManifestChangedFilePath(),
                history.getManifestUpdatedAt(),
                execution.startedAt(),
                execution.finishedAt(),
                execution.createdAt()
        );
    }

    static BuildProfileRunResponse failed(
            Long sourceRepositoryId,
            Long buildProfileId,
            String buildProfileName,
            Long historyId,
            String repositoryName,
            String repositoryUrl,
            BuildProfileCiTool ciTool,
            String workingDirectory,
            String requestedBy,
            String requestedValue,
            String branch,
            String dispatchTarget,
            Long portalRequestId,
            String statusMessage
    ) {
        return new BuildProfileRunResponse(
                sourceRepositoryId,
                buildProfileId,
                buildProfileName,
                historyId,
                null,
                portalRequestId,
                repositoryName,
                repositoryUrl,
                ciTool,
                workingDirectory,
                requestedBy,
                requestedValue,
                branch,
                dispatchTarget,
                "FAILED",
                statusMessage,
                null,
                null,
                null,
                null,
                "",
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                java.time.Instant.now()
        );
    }
}
